  version: '3'

  services:
    develop:
      image: maven:3.6.3-openjdk-16
      volumes:
      - .:/workspaces/quizweb
      command: /bin/sh -c "while sleep 1000; do :; done"     
  networks:
    default:
        external:
          name: quizweb_app_net