  version: '3'

  services:
    develop:
      image: maven:3.8.1-jdk-11
      volumes:
      - .:/workspaces/quizweb
      # - react_zone:/workspaces/quizweb/src/main/resources/static/react
      - war_deploy:/workspaces/quizweb/build/deploy
      - /home/water/.ssh:/root/.ssh
      networks:
        develop_net:
          ipv4_address: 172.22.0.10
      command: /bin/sh -c "while sleep 1000; do :; done"
    mysql:
      image: mysql:8.0.20
      expose:
        - '3306'
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: QUIZ
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes: 
        - ./sql/firstSql:/docker-entrypoint-initdb.d
        - ./conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        # - db_data:/var/lib/mysql
      networks:
        develop_net:
          ipv4_address: 172.22.0.3
      ports:
      - '3306:3306'
    tomcat:
      image: tomcat:9-jdk8-temurin
      # https://stackoverflow.com/questions/9620723/eclipse-failed-to-connect-to-remote-vm-connection-refused
      # デフォルトだとループバックアドレスになってしまうので別コンテナからアクセスできない
      environment:
        - JPDA_ADDRESS=0.0.0.0:8000
      ports:
      - '8080:8080'
      - '8081:8081'
      expose:
      - '8009'
      - '8000'
      volumes:
        - ./conf/tomcat/conf:/usr/local/tomcat/conf
        - war_deploy:/usr/local/tomcat/webapps
        # - ./target/quizWeb.war:/usr/local/tomcat/webapps/quizWeb.war
        # - images:/usr/local/tomcat/webapps/quizWeb/WEB-INF/classes/static/img
      command: catalina.sh jpda run
      networks:
        develop_net:
          ipv4_address: 172.22.0.5
  
  networks:
    develop_net:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.22.0.1/24

  volumes:
    war_deploy:
    react_zone:
    images:    